name: Deploy ADF

on:
    push:
        branches:
        - main

permissions:
  id-token: write
  contents: read
 
  
jobs:
  deploy_adf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pause all triggers
        if: false
        run: |
          echo "Pausing all triggers"
          for file in ./trigger/*
          do
            jq '.properties.runtimeState="Stopped"' $file | tee trigger/temp.json >/dev/null
            mv trigger/temp.json $file
            echo "Set trigger runtimeState to 'Stopped' for $file"
          done
      - name: Export ARM Template
        id: export
        uses: Azure/data-factory-export-action@v1.2.1
        with:
          path: ./
          id: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ vars.RG_DEV_NAME }}/providers/Microsoft.DataFactory/factories/${{ vars.DF_NAME }}
      - name: Overwrite references in ARM Template
        if: false
        run: |
          echo "Start overwriting references in ARMTemplateForFactory.json and ARMTemplateParametersForFactory.json using the mappings in env_mappings.json"
          jq -c 'to_entries[]' env_mappings.json | while read line; do 
              old=$( jq -r '.key' <<< "$line" )
              new=$( jq -r '.value' <<< "$line" )
              echo "Replace $old by $new"
              sed -i "s|$old|$new|g" ${{ steps.export.outputs.arm-template-directory }}/ARMTemplateForFactory.json
              sed -i "s|$old|$new|g" ${{ steps.export.outputs.arm-template-directory }}/ARMTemplateParametersForFactory.json
          done
      - name: Publish ARM template
        uses: actions/upload-artifact@v2
        with:
          name: adf-artifact
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error    
      - name: Copy ARM Template to root
        run: cp -a armTemplate/. . 
      - name: AZ OIDC login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENENT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true      
      - name: Add datafactory extension to AZ CLI
        run: az extension add --name datafactory
      - name: Deploy resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ vars.RG_DEV_NAME }}
          dataFactoryName: ${{ vars.DF_NAME }}
          armTemplateFile: ARMTemplateForFactory.json